### ISSUE TITLE
[Feature] Integrate Silent Service Like in the Old Android App

### ISSUE THREAD

**Issue by Wladefant** [TUM-Dev/campus_flutter#105]
I think that would be a neat future even though I am a new student and havent used it yet

**Comment by jakobkoerber** [comment]
What exactly do you mean by Silent Service?

**Comment by jakobkoerber** [comment]
Thanks for clearing that up! Unfortunately this not possible on iOS due to the lack of permissions. We could think about enabling it on Android. But the motion of moving Flutter was to ensure feature parity and I'm not sure how useful it is. Could be easier to have your OS look into your calendar ^^ this can be, at least on iOS, easily achieved

**Comment by Wladefant** [comment]
Yeah, but that does not mean there cant be any os specific features in the app, right?

**Comment by jakobkoerber** [comment]
In my opinion it kind of does but I will give it a try :)

**Comment by kordianbruck** [comment]
I think the silent service was cool until like 5 years ago. Today a lot of phones have this feature natively: https://support.google.com/android/answer/9069335?hl=en

Given we can only implement it on one platform (and it was a bit buggy when we had it) I'd say this is infeasible. I'd rather spend the dev cycles on features that are useful to our entire userbase.
